general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on  # Força o sinal de volta após o sleep
}

# [AVISO] 2 minutos e meio - Diminui o brilho da tela para avisar que vai bloquear
listener {
    timeout = 150                                 # Tempo em segundos (2.5 minutos)
    on-timeout = brightnessctl set 10%            # Reduz o brilho (requer o pacote brightnessctl)
    on-resume = brightnessctl set 100%            # Volta o brilho ao normal se você mexer o mouse
}

# [BLOQUEIO] 3 minutos - Tranca a tela oficialmente
listener {
    timeout = 180                                 # Tempo em segundos (3 minutos)
    on-timeout = loginctl lock-session            # Chama o comando de lock geral do sistema
}

# [ECONOMIA DE ENERGIA] 5 minutos - Desliga o sinal de vídeo dos monitores (DPMS)
listener {
    timeout = 300                                 # Tempo em segundos (5 minutos)
    on-timeout = hyprctl dispatch dpms off        # Desliga os monitores (HDMI/DP)
    on-resume = hyprctl dispatch dpms on          # Religa os monitores ao detectar atividade
}
