general {
  gaps_in = 5
  gaps_out = 10
  resize_on_border = true  # Permite redimensionar arrastando as bordas com o mouse
  extend_border_grab_area = 15 # Aumenta a área de clique da borda para ficar mais fácil acertar com o mouse
}

decoration {
  rounding = 15
  rounding_power = 2

  shadow {
    enabled = true
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
  }

  blur {
    enabled = true
    size = 3
    passes = 2
    vibrancy = 0.1696
  }
}
